#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-opal_errd-000 -q

check_suite
copy_sysfs

./opal_errd -s $SYSFS -o $OUT/platform -D -e /bin/true 2>&1 \
    | sed -e 's/ELOG\[[0-9]*\]/ELOG[XXXX]/' > $LOG

ls -1 $OUT >> $LOG
(cd $OUT/platform; md5sum *) | sort  -t ' ' -k 2 | sed 's/ .*-/  /g'  >> $LOG

diff_with_result $LOG

register_success
