#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-opal-elog-parse-003 -q

check_suite
copy_sysfs

run_binary "./opal-elog-parse/opal-elog-parse" "-d 3 -f $SYSFS/firmware/opal/elog/0x03/raw"
R=$?
if [ $R -ne 234 ]; then
	register_fail $R;
fi

diff_with_result

register_success
