#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-opal_errd-000 -q

check_suite
copy_sysfs

run_binary "./opal_errd" "-s $SYSFS -o $OUT/platform -D -e /bin/true"
sed -e 's/ELOG\[[0-9]*\]/ELOG[XXXX]/' -i $OUTSTDERR
# On qemu pseries it prints PowerKVM Guest. Make travis CI happy
sed -e 's/PowerKVM/PowerVM/' -i $OUTSTDERR
sed -e 's/Guest/LPAR/' -i $OUTSTDERR

ls -1 $OUT >> $OUTSTDOUT
if [[ -x $OUT/platform ]] ; then
	(cd $OUT/platform; md5sum *) | sort  -t ' ' -k 2 | awk  -F'[- ]' '{print $1"  "$4}'  >> $OUTSTDOUT
fi
diff_with_result

register_success
