#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-opal_errd-002 -q

check_suite
copy_sysfs


-./opal_errd -s /not/a/sysfs -o $OUT/platform -D -e /bin/true 2>&1 \
	| sed -e 's/ELOG\[[0-9]*\]/ELOG[XXXX]/' >> $LOG

RC=${PIPESTATUS[0]}
if [ "$RC" -ne 255 ] ; then
	register_success $RC;
fi

register_success
