#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-extract_opal_dump-000 -q

check_suite
copy_sysfs

run_binary "./extract_opal_dump" "-s $SYSFS -o $OUT"
sed -e 's%/tmp/.*/%%;s/OPAL_DUMP\[[0-9]*\]/OPAL_DUMP[XXXX]/' -i $OUTSTDERR

ls -1 $OUT >> $OUTSTDOUT
(cd $OUT; md5sum *) >> $OUTSTDOUT

diff_with_result;

register_success
