#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-opal-elog-parse-006 -q

check_suite
copy_sysfs

run_binary "./opal-elog-parse/opal-elog-parse" "-d 0x5055ed2e -f $SYSFS/firmware/opal/elog/0x5055ed2e/raw"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

diff_with_result

register_success
