#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-bh-001-structs -q


run_binary "./bh_structs"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

diff_with_result

register_success
