#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-slider-003-healthy_diag_encl -q


#copying vpd file
cp slider.vpd slider_healthy.vpd

# Generate pg2 file
run_binary "./slider_mk_healthy" "slider_healthy.pg2"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

run_binary "./../diag_encl" "-v -f slider_healthy.pg2 sg8"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

diff_with_result

rm slider_healthy.vpd
rm slider_healthy.pg2

register_success
