#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-bh-002-mk_healthy -q

run_binary "./bh_mk_healthy" "bluehawk_healthy.pg2"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

diff_with_result bluehawk_healthy.pg2

rm bluehawk_healthy.pg2
register_success
