#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-bh-003-healthy_diag_encl -q


#copying vpd file
cp bluehawk.vpd bluehawk_healthy.vpd

# Generate pg2 file
run_binary "./bh_mk_healthy" "bluehawk_healthy.pg2"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

run_binary "./../diag_encl" "-v -f bluehawk_healthy.pg2 sg8"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

diff_with_result

rm bluehawk_healthy.vpd
rm bluehawk_healthy.pg2

register_success
