#!/bin/bash

#WARNING: DO NOT RUN THIS FILE DIRECTLY
#  This file expects to be a part of ppc64-diag test suite
#  Run this file with ../run_tests -t test-bh-005-hot_power_diag_encl -q

# Copying fake VPD data
cp bluehawk.vpd bluehawk_hot_power.vpd

# Generate pg2 file
run_binary "./bh_mk_hot_power" "bluehawk_hot_power.pg2"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

run_binary "./../diag_encl" "-v -f bluehawk_hot_power.pg2 sg8"
R=$?
if [ $R -ne 0 ]; then
	register_fail $R;
fi

diff_with_result
rm bluehawk_hot_power.vpd
rm bluehawk_hot_power.pg2

register_success
