.\"
.\" Copyright (C) 2022, 2023 IBM Corporation
.\"
.TH "DIAG_NVME" "8" "September 2023" "Linux" "PowerLinux Diagnostic Tools"
.hy
.SH NAME
.PP
diag_nvme \- diagnose NVMe devices
.SH SYNOPSIS
.PP
\f[B]diag_nvme\f[] [<\f[B]nvme\f[]\f[I]n\f[] \&...>]
.PD 0
.P
.PD
\f[B]diag_nvme\f[]
<\f[B]nvme\f[]\f[I]n\f[]>
.PD 0
.P
.PD
\f[B]diag_nvme\f[] --help
.SH DESCRIPTION
.PP
The \f[B]diag_nvme\f[] command retrieves the SMART data from the NVMe
device(s) specified and report failures detected through events created
in the servicelog database.
If no device is specified, all NVMe devices detected in the system will
go through the diagnostics procedure.
.PP
The user can control which events will be reported through the
configuration file \f[I]/etc/ppc64\-diag/diag_nvme.config\f[]
.SH OPTIONS
.B \f[B]diag_nvme nvme0 nvme1\f[]
Run diagnostics only in nvme0 and nvme1 devices.
.RS
.RE
.SH REPORTING BUGS
.PP
Patches and issues may be submitted at
https://github.com/power\-ras/ppc64\-diag/
.SH FILES
.TP
.B \f[I]/etc/ppc64\-diag/diag_nvme.config\f[]
Configuration file to select which events to report to the servicelog
database.
.RS
.RE
.TP
.B \f[I]/etc/cron.daily/run_diag_nvme\f[]
Script to run diag_nvme in the system on a daily basis.
.RS
.RE
.SH SEE ALSO
.PP
\f[B]servicelog\f[](8)
.SH AUTHORS
Murilo Fossa Vicentini
