.TH add_regex: "8" "June 2016" "ppc64-diag" "System Administration Utilities"
.SH NAME
add_regex \- catalog parser
.SH SYNOPSIS
.B add_regex 
[\fB\-C\fR \fI\,dir\/\fR]
.SH DESCRIPTION
Parse all the catalog files in the specified directory, populating
reporter_catalog, exceptions catalog, and event_catalog.
.SH OPTIONS
.TP
.BR \-C " " \fIdir\fR
Catalog directory in which catalog files are stored.
