.TH extract_platdump "8" "June 2016" "ppc64-diag" "System Administration Utilities"
.SH NAME
extract_platdump: \- Extract platform dump
.SH SYNOPSIS
.B extract_platdump
[\fI\,-h\/\fR] [\fI\,-v\/\fR] \fI\,<dump_tag>\/\fR
.SH DESCRIPTION
Extracts a platform dump with a given tag to the filesystem. \fI\,<dump_tag>\fR is the tag of the dump(s) to extract, in hex.
.HP
\fB\-h\fR: print this help message
.HP
\fB\-v\fR: verbose output
