#!/bin/bash

SYSFS=`mktemp -d --tmpdir extract_opal_dump_sysfs.XXXXXXXXXX`
OUT=`mktemp -d --tmpdir extract_opal_dump.XXXXXXXXXX`
OUTERR=`mktemp --tmpdir extract_opal_dump.stderr.XXXXXXXXXX`
LOG=`mktemp --tmpdir extract_opal_dump.out.XXXXXXXXXX`

cp -pr sysfs-test/* $SYSFS/

./extract_opal_dump -s $SYSFS -o $OUT 2> $OUTERR

echo 'test-extract_opal_dump' > $LOG
cat $OUTERR | sed -e 's%/tmp/.*/%%;s/OPAL_DUMP\[[0-9]*\]/OPAL_DUMP[XXXX]/' >> $LOG
ls -1 $OUT >> $LOG
(cd $OUT; md5sum *) >> $LOG

if diff -u test-extract_opal_dump.result $LOG; then
	rm -rf $SYSFS $OUT $LOG
	echo PASS;
else
	echo FAIL;
fi
