#!/bin/bash

SYSFS=`mktemp -d --tmpdir opal-elog-parse.sysfs.XXXXXXXXXX`
OUT=`mktemp -d --tmpdir opal-elog-parse.log.XXXXXXXXXX`
LOG=`mktemp --tmpdir opal-elog-parse.out.XXXXXXXXXX`

cp -pr sysfs-test/* $SYSFS/

echo 'test-opal-elog-parse' > $LOG

./opal_errd -s $SYSFS -o $OUT/platform -D -e /bin/true 2>&1 \
    | sed -e 's/ELOG\[[0-9]*\]/ELOG[XXXX]/' >> $LOG

./opal-elog-parse/opal-elog-parse -l -f $OUT/platform >> $LOG

if diff -u test-opal-elog-parse.result $LOG; then
	rm -rf $SYSFS $OUT $LOG
	echo PASS;
else
	echo FAIL;
fi
